### ISSUE TITLE
material list

### ISSUE THREAD

**Issue by googlescientificnameforapig** [kult0922/minecraftDot#2]
I play in survival and I want a material list so I don't have to estimated

**Comment by kult0922** [comment]
You can download block list csv file from "Download csv" button.
![image](https://user-images.githubusercontent.com/38486600/185726046-cddd716c-27a6-422f-a25f-bbb41085328d.png)

**Comment by kult0922** [comment]
@googlescientificnameforapig 
material list is in bottom of csv file.
![image](https://user-images.githubusercontent.com/38486600/185726057-a8ad249d-9e83-4e23-8554-75569bfa7fe9.png)
